sudo: false
language: ruby
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2' --no-rdoc --no-ri
